version: 0.5.5.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
environment:
  sigsec:
    secure: xPHd63T1ITC08g7rnFgmRpGWYPefxI1ju5a778fpDUbmPM8bAruUspLcu3Rkt7sB
build_script:
- ps: >-
    nuget install secure-file -ExcludeVersion

    secure-file\tools\secure-file -decrypt appveyor.snk.enc -secret %sigsec%

    Build\runbuild.ps1

    move -Path Working\phrogGLControl*.zip -Destination .

    move -Path Working\NuGet\*.nupkg -Destination .

test: off
artifacts:
- path: phrogGLControl*.zip
- path: '*.nupkg'
  name: nuget
deploy:
- provider: NuGet
  api_key:
    secure: rTP0g5fsIZb4ob+1hwFZehSwBHebhIH7yMNyxPg9Lu50/3VRAzkg0v8mDqUt7ItX
  artifact: nuget
  on:
    appveyor_repo_tag: true